### ISSUE TITLE
Update example config for "Use the HTTP input plugin

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#1303]
Update this...
https://v2.docs.influxdata.com/v2.0/write-data/no-code/use-telegraf/use-telegraf-plugins/use-http-plugin/#example-configuration

with this...
```toml
[[inputs.http]]

  # URL for NYC's Citi Bike station data in JSON format
  urls = ["https://gbfs.citibikenyc.com/gbfs/en/station_status.json"]

  # Overwrite measurement name from default `http` to `citibikenyc`
  name_override = "citibike"

  # Exclude url and host items from tags
  tagexclude = ["url", "host"]

  # Data from HTTP in JSON format
  data_format = "json"

  # Parse data in `data.stations` path only
  json_query = "data.stations"

  #Set station metadata as tags
  tag_keys = ["station_id"]

  # JSON values to set as string fields
  json_string_fields = []

  # Latest station information reported at `lastCommunicationTime`
  json_time_key = "last_reported"

  # Time is reported in Golang "reference time" format
  json_time_format = "unix"
```

...to address broken link
