### ISSUE TITLE
OPC UA Input Plugin Docs

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#1398]
_Describe the issue here._
People using the OPC UA Input Plugin will fall into the category for potentially less developer/technical users, so our documentation for these plugins will need to be really clear. Would like to include some configuration examples with screenshots of Prosys & Kepware interfaces. 

[OPC UA Input Plugin readme](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/opcua)

I'll add config examples as I pull them together here.

**Comment by sjwang90** [comment]
[Prosys Simulator](https://www.prosysopc.com/products/opc-ua-simulation-server/) Example:
For node: `name = "Random"`
![image](https://user-images.githubusercontent.com/32681364/92534949-f13a6a00-f1ea-11ea-8db8-9201ddc69f68.png)

For node: `name = "Triangle"`
![image](https://user-images.githubusercontent.com/32681364/92535012-1cbd5480-f1eb-11ea-9ba1-697a4693427f.png)


Sample Input
```toml
[[inputs.opcua_client]]
  name = "opcua"
  endpoint = "opc.tcp://MBP15-SWANG.local:53530/OPCUA/SimulationServer"
  security_policy = "Basic256"
  security_mode = "Sign"
  nodes = [
      {name="Random", namespace="3", identifier_type="i", identifier="1002", data_type="double", description="Prosys OPC UA Simulation Server"},
      {name="Triangle", namespace="3", identifier_type="i", identifier="1006", data_type="double", description="Prosys OPC UA Simulation Server"},
  ]
```


Sample Output
```
opcua,host=MBP15-SWANG.local,name=Random,type=double Random=1.746295 1599604830000000000
opcua,host=MBP15-SWANG.local,name=Triangle,type=double Triangle=0 1599604830000000000
```


![image](https://user-images.githubusercontent.com/32681364/92534859-bb958100-f1ea-11ea-9ab3-0f179b598195.png)
