### ISSUE TITLE
Document how to use Kapactor with InfluxDB 2.0

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1804]
We need to document using Kapacitor with InfluxDB 2.0. This should live in the Kapacitor docs. Some important notes to cover:

- InfluxDB 2.0 doesn't have a subscriptions API, so it doesn't natively support Kapacitor stream tasks. To use stream tasks, you can use Telegraf to write directly to Kapacitor (and InfluxDB):

    ##### Example Telegraf configuration
    ```toml
    # Write to Kapacitor
    [[outputs.influxdb]]
      urls = ["http://localhost:9092"]
      database = "example-db"
      retention_policy = "example-rp"

    # Write to InfluxDB 2.0
    [[outputs.influxdb_v2]]
      urls = ["http://localhost:8086"]
      token = "$INFLUX_TOKEN"
      organization = "example-org"
      bucket = "example-db/example-rp"
    ```

- The 2.0 v1 compatibility APIs allow batch tasks to work without modification, but users may need to create DBRP mappings.
