### ISSUE TITLE
Telegraf: Add examples of running processors in order

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#2323]
**Add some example scenarios for ordering processors**
Relevant docs page: https://docs.influxdata.com/telegraf/v1.17/administration/configuration/#processor-configuration

`order = n` must be configured to run all involved processors in specific sequence.  
https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#processor-plugins

**Possible examples:**

1. [GeoIP Processor](https://github.com/a-bali/telegraf-geoip)(external plugin) + [S2 Geo Processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/s2geo)
```toml
[[processors.execd]]
  order = 1
  command = ["/path/to/geoip_binary", "--config", "/path/to/geoip_config_file"]

[[processors.s2geo]]
  order = 2
  ## The name of the lat and lon fields containing WGS-84 latitude and
  ## longitude in decimal degrees.
  lat_field = "lat"
  lon_field = "lon"

  ## New tag to create
  tag_key = "s2_cell_id"

  ## Cell level (see https://s2geometry.io/resources/s2cell_statistics.html)
  # cell_level = 9
```

2. https://github.com/influxdata/telegraf/issues/8016 example
```toml
[[inputs.file]]
  name_override = "filesystems_raw"
  files = ["./json.txt"]
  data_format = "value"
  data_type = "string"

[[processors.parser]]
  metric_name = "filesystems"
  order = 1
  namepass = "filesystems_raw"
  drop_original = false
  parse_fields = ["value"]
  data_format = "json"
  json_strict = true
  json_query = "filesystems./"
  tag_keys = [
    "mount",
    "device"
  ]

[[processors.parser]]
  metric_name = "filesystems"
  order = 2
  namepass = "filesystems_raw"
  drop_original = false
  parse_fields = ["value"]
  data_format = "json"
  json_strict = true
  json_query = "filesystems./usr"
  tag_keys = [
    "mount",
    "device"
  ]

[[processors.strings]]
  order = 3
  namepass = "filesystems_raw"
  fielddrop = ["value"] # deletes the metric

[[outputs.file]]
  namedrop = "filesystems_raw"
  files = ["stdout"]
```

***Implementation of this [feature](https://github.com/influxdata/telegraf/issues/8697) will add additional ordering capabilities
