### ISSUE TITLE
add a docker-compose example to the oss setup docs

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2700]
We should add the following docker-compose file to the oss setup section of the docs so that someone setting up docker can see an example using the docker setup env vars:

```
version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdbv2:/.influxdbv2
      - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt
      - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=russ
      - DOCKER_INFLUXDB_INIT_PASSWORD=something
      - DOCKER_INFLUXDB_INIT_ORG=InfluxData
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    ports:
      - "8086:8086"
volumes:
  influxdbv2:
```

see also #2699
