### ISSUE TITLE
Write data to OSS and Cloud (aka dual write scenario

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3321]
Write Data to OSS and Cloud (aka Dual Write scenario)
a. Describe Telegraf setup for dual write within https://docs.influxdata.com/influxdb/v2.0/write-data/no-code/use-telegraf/ (This content applies to both Cloud and OSS....can be used in both places).

cc @timhallinflux for review

**Comment by sjwang90** [comment]
Sample dual write config:

```toml
[[inputs.cpu]]
[[inputs.mem]]

## any other inputs, processors, aggregators that you want to include into your config
## without any namepass, tagpass filters or settings changes your data should get identically written to the two outputs below

# Send data to InfluxDB OSS v2
[[outputs.influxdb_v2]]	
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ## urls exp: http://127.0.0.1:9999
  urls = ["http://localhost:8086"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "influxdata"

  ## Destination bucket to write into.
  bucket = "telegraf"

# Send data to InfluxDB cloud - AWS West cloud instance
 [[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.

  urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "swang@influxdata.com"

  ## Destination bucket to write into.
  bucket = "telegraf"
 ```
