### ISSUE TITLE
Verify no blank pages due to Hugo update

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3820]
Previously, hugo supported linking to an external site by adding the site `url` in front matter:

```
menu:
  telegraf_20_1:
    name: Example name
    url: https://some-external-url.com
```

Now, if a page has the frontmatter above, you'll see a blank page. 

To fix, update the frontmatter to include `url` as a `params`:

```
menu:
  telegraf_20_1:
    name: Example name
    params:
      url: https://some-external-url.com/
```

**Search and replace all docs under content:**

- [x] influxdb @sanderson completed
- [ ] telegraf @noramullen1 
- [ ] chronograf @lwandzura 
- [x] kapacitor @lwandzura 
- [ ] enterprise @lwandzura
