### ISSUE TITLE
Possible missing TLS information

### ISSUE THREAD

**Issue by lwandzura** [influxdata/docs-v2#4051]
User feedback :

"The "run influxd with TLS flags" is missing information for installs using a systemd service. I think I need to edit /usr/lib/influxdb/scripts/influxd-systemd-start.sh but am not sure where or with what."

https://docs.influxdata.com/influxdb/v2.2/security/enable-tls/

**Comment by andrew-aiken** [comment]
Pretty old ticket, was setting this up myself

Update the start config (`/usr/lib/influxdb/scripts/influxd-systemd-start.sh`) to replace
```bash
/usr/bin/influxd &
```
With (update your cert paths)
```bash
/usr/bin/influxd --tls-cert "/etc/ssl/influxdb-selfsigned.crt" --tls-key "/etc/ssl/influxdb-selfsigned.key" &
```

**Comment by andrew-aiken** [comment]
Actually a better way would be to update the config (`/etc/influxdb/config.toml`) and add the following lines

```toml
tls-cert = "/etc/ssl/influxdb-selfsigned.crt"
tls-key = "/etc/ssl/influxdb-selfsigned.key"
```
