### ISSUE TITLE
Unclear v1 compatibility

### ISSUE THREAD

**Issue by rinmalavi** [influxdata/docs-v2#4393]
From [v1 compatibility page](https://docs.influxdata.com/influxdb/v2.4/api/v1-compatibility/) i assumed you could start your influx with lets say (docker-compose)
 
```
  influx2:
    image: influxdb:2.4.0
    volumes:
      - ./dev/influxdb2:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: dev
      DOCKER_INFLUXDB_INIT_PASSWORD: 12345678
      DOCKER_INFLUXDB_INIT_ORG: com.some
      DOCKER_INFLUXDB_INIT_BUCKET: m2_dev
      DOCKER_INFLUXDB_INIT_MODE: setup
```
 
fill it up, and then curl 

``` sh
curl --get "http://localhost:8086/query" \
    --data-urlencode "u=dev" \
    --data-urlencode "p=12345678" \
    --data-urlencode "db=m2_dev" \
    --data-urlencode "q=SELECT * FROM default"
 ```
 
 Get some results, not `{"code":"unauthorized","message":"Unauthorized"}`
