### ISSUE TITLE
"Use Docker Compose" instructions for InfluxDB 3 are incomplete

### ISSUE THREAD

**Issue by ThoWoKi** [influxdata/docs-v2#5948]
The instructions for "Use Docker Compose" are incomplete on docs.influxdata.com.
(Git-File is fine)

```
# compose.yaml
services
  influxdb3-core:
    container_name: influxdb3-core
    image: quay.io/influxdb/influxdb3-core
```

The rest of the docker-compose-file is in a single line under the code-block. 

```:latest ports: - 9999:9999 command: - serve - –node-id=node0 - –log-filter=debug - –object-store=file - –data-dir=/var/lib/influxdb3```

Issue seems to be the following line in **install.md**: 

[https://github.com/influxdata/docs-v2/blob/46dad240b95c752f1fac45b975abc7de762958e7/content/influxdb3/core/install.md?plain=1#L175](https://github.com/influxdata/docs-v2/blob/46dad240b95c752f1fac45b975abc7de762958e7/content/influxdb3/core/install.md?plain=1#L175)

Looks like the variable `{{% product-key %}}` kills the format.

##### Relevant URLs
- https://docs.influxdata.com/influxdb3/core/install/#use-docker-compose
- Git: https://github.com/influxdata/docs-v2/blob/master/content/influxdb3/core/install.md
