### ISSUE TITLE
documentation mentions --plugins-dir option for docker compose, but it does not exist

### ISSUE THREAD

**Issue by FireHawken** [influxdata/docs-v2#6150]
Chapter "Docker Compose" has this snippet:

```
# compose.yaml
services:
  influxdb3-enterprise:
    container_name: influxdb3-enterprise
    image: influxdb:3-enterprise
    ports:
      - 8181:8181 
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --cluster-id=cluster0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
      - --plugins-dir=/var/lib/influxdb3-plugins
      - --license-email=${INFLUXDB3_LICENSE_EMAIL}
```
However, launching the latest version of influxdb3-enterprise results in immediate exit with the following log entries:
```
influxdb3-enterprise  | error: unexpected argument '--plugins-dir' found
influxdb3-enterprise  |
influxdb3-enterprise  |   tip: a similar argument exists: '--plugin-dir'
influxdb3-enterprise  |
influxdb3-enterprise  | Usage: influxdb3 serve --cluster-id <CLUSTER_IDENTIFIER_PREFIX> --object-store <object-store> --data-dir <data-dir> --plugin-dir <PLUGIN_DIR> <--node-id <PREFIX>|--node-id-from-env <FROM_ENV_VAR>>
influxdb3-enterprise  |
influxdb3-enterprise  | For more information, try '--help'.
influxdb3-enterprise exited with code 2
```
I assume there is typo in `--plugins-dir` option, which should be `--plugin-dir` in fact.

##### Relevant URLs
- https://docs.influxdata.com/influxdb3/enterprise/install/
